CC = gcc
CFLAGS = -Wall -O2
LDFLAGS = -lwiringPi  # Añadir las bibliotecas necesarias
ASM = as

all: main

main: main.o sequences.o sequences.o sequences.o
    $(CC) -o main main.o sequences.o sequences.o $(LDFLAGS)

main.o: main.c
    $(CC) $(CFLAGS) -c main.c

sequences.o: sequences.c
    $(CC) $(CFLAGS) -c sequences.c

sequences.o: sequences.S
    $(ASM) -o sequences.o sequences.S

clean:
    rm -f *.o main
